### ISSUE TITLE
Wrapping fixes in editor transactions

### ISSUE THREAD

**Issue by ahrenm** [Netflix-Skunkworks/UnrealValidationFramework#4]
Hi there,
Not so much an issue, more a design question.

When making actor level updates in VP I always wrap the changes in editor transactions to ensure they propagate over multi-user. I understand the the Validation Framework is designed to be used "before" the project hits a stage. 

On the flip side, during look/dev iteration (which we often do on a wall), I've seen all sorts of rando changes sneak into a map. Being able to hot apply fixes to things like post processing and ICVFX could streamline the workflow.

I'm happy to tweak the relevant validations/fixes if you're ok with the concept.

Ahren M

**Comment by davisadam10** [comment]
Yeah, I'm with you, the intent is that really people should be running preflight/validation checks before every take. This is just good practice and is the mindset we want to get operators to be shifting toward checking rather than assuming.

If you're happy to branch off (from dev) and take a look I think there are a lot of benefits from making sure these work in a multiuser setup. We just need to ensure that we do not become dependent on the multiuser setup which with the transactions im not sure we would.

We still need/want this to be able to work say as part of a CI, or artist workflow outside of a multiuser session etc.

I'd say branch off, change one of the validations so it works this way, lets's make sure it all still works and covers the various needs and if so we green light changing the rest of the validations.

**Comment by ahrenm** [comment]
Couldn't agree more. I think there is definitely room for a "preflight" group. I'd be looking at settings that are frequent creative or technical tweaks that are applied to a setup/shot. And perhaps some sensible defaults stored in the VP Settings. I know that a CineCamera aperture override is one that trips us up from to time ;-)

With regards to MU "transactions" (and please skip over this if you're already familiar):
The transactions themselves aren't anything special, they're just copied from the Editors Undo/Redo log. The MU Client just attaches onto this log and pipes them out over the network. Props to Epic, it's a sneaky implementation. Pretty much every action in the editor already generates Undo/Redo logs, so they got the data for free.

The caveat is that it does require the "Editor" module to be present. This is why nDisplay nodes can't generate MU transactions, because they're running in 'game' space & the editor module is not present. As the ValidationFramework module is an Editor module, anywhere that it can launch should by definition have access to the correct API. There is no dependency on MU in this code.

The ICVFX Aspect Ratio plugin I submitted has the updates wrapped if you want to see a live sample. Even put comments in :-)

**Comment by davisadam10** [comment]
This validation has been included in the 1.2.0 update for UE 5.2
Further, all the validations have been udpated to make use of the Transactions system so work during a multi user session.
Each Validation creates its own undo stack
